### ISSUE TITLE
Support for reCAPTCHA Enterprise - 

### ISSUE THREAD

**Issue by chenop** [douglasjunior/react-native-recaptcha-that-works#12]
Hi,
Thanks for this package "that just works" :-)

We are considering upgrading to reCAPTCHA Enterprise - does this package support it?

**Comment by douglasjunior** [comment]
Hi @chenop, I dont know about reCAPTCHA Enterprise, do you have any documentation about it?

**Comment by chenop** [comment]
[Comparison](https://cloud.google.com/recaptcha-enterprise/docs/compare-versions)
[Recaptcha Enterprise](https://cloud.google.com/recaptcha-enterprise)

**Comment by douglasjunior** [comment]
Looks like the client migration is simple.

![image](https://user-images.githubusercontent.com/1512341/127492431-59b6b8f5-a8a0-4742-a1bb-a9fc381c5394.png)

**Comment by maxwell353** [comment]
Efetuei as modificações no arquivo get-template.js referente a https://cloud.google.com/recaptcha-enterprise/docs/using-features, mas mesmo assim minha sitekey não funciona.
Sua chave api:  6LejsqwZAAAAAGsmSDWH5g09dOyNoGMcanBllKPF, funciona corretamente.
Minha chave: 6LeWo-0bAAAAAEUZsokYlBi8E6LiXjIV87KrQL-w, retorna erro null.
Se possível demonstre o procedimento para criar uma sitekey.

**Comment by victor-cui-brigit** [comment]
Will the library work out of the box? when creating a mobile reCAPTCHA key for enterprise, it says to specify iOS or Android.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/91908469/144063854-8ef7371f-c486-4cd5-906e-06ceb88b4ff8.png">

**Comment by douglasjunior** [comment]
Today, this library uses WebView to work with reCAPTCHA v2 only. Currently, we have no plan to implement Enterprise mobile reCAPTCHA. 

But, any contributions are welcome.

**Comment by victor-cui-brigit** [comment]
hmm I created a reCAPTCHA v3 key on https://www.google.com/u/1/recaptcha/admin/site/493612296 (not enterprise) and the library was able to verify and generate a token. Perhaps the library will work with v3 as long as it's not enterprise mobile?

**Comment by douglasjunior** [comment]
Done in 1.2.0 https://github.com/douglasjunior/react-native-recaptcha-that-works/releases/tag/1.2.0

**Comment by Oliveirax** [comment]
Does this lib work with recaptcha enterprise? If yes, then how? I created ios and android keys, as well as a web key and every one of them returns "Error: null" from the error callback. for a brief moment, we can see an error in the device screen
![IMG_4211](https://user-images.githubusercontent.com/13275085/207409014-80811997-c1b1-468f-a807-63d1f04349b1.PNG)

**Comment by douglasjunior** [comment]
> Does this lib work with recaptcha enterprise? If yes, then how? I created ios and android keys, as well as a web key and every one of them returns "Error: null" from the error callback. for a brief moment, we can see an error in the device screen !

Nothing special, just add `enterprise={true}`:

```js
            <Recaptcha
                ref={recaptcha}
                siteKey="<your-recaptcha-public-key>"
                baseUrl="http://my.domain.com"
                onVerify={onVerify}
                onExpire={onExpire}
                enterprise={true}
            />
```

**Comment by Oliveirax** [comment]
Yes. I got that. But that is not the issue. The issue is how do I fill in the baseUrl field?  iOS and Android keys don't have a baseURL / domain to define. You only define the app package name.  And a web key does have a domain to define, but still does not work. What am I doing wrong?

My code:
`const RecaptchaTest: React.FC = () => {
  const recaptcha = useRef<RecaptchaHandles>(null)

  const handleOpen = useCallback(() => {
    console.log('open button!')
    recaptcha.current?.open()
  }, [])

  const handleClose = useCallback(() => {
    console.log('close button!')
    recaptcha.current?.close()
  }, [])

  const onLoad = () => {
    console.log('load!')
  }

  const onVerify = (token: string) => {
    console.log('success!', token)
  }

  const onExpire = () => {
    console.log('expired!')
  }

  const onError = (error: string) => {
    console.log('Error: ', error)
  }

  const onClose = () => {
    console.log('Close!')
  }

  return (
    <View>
      <Recaptcha
        ref={recaptcha}
        lang="en"
        headerComponent={<Button title="Close" onPress={handleClose} />}
        siteKey="6LckJ1gjAAAAAPUcfXRG3khTGDRJxiMTim-8ph1N"
        baseUrl="com.anova.unify.go"
        onVerify={onVerify}
        onExpire={onExpire}
        onError={onError}
        onLoad={onLoad}
        onClose={onClose}
        size="normal"
        enterprise={true}
        action={'login'}
        hideBadge={false}
      />
      <Button title="Open" onPress={handleOpen} />
    </View>
  )
}
`

**Comment by douglasjunior** [comment]
Take a look at #34

**Comment by Oliveirax** [comment]
> Got it working, but with two small caveats: I used the web key (not the iOS or Android key), and used the prop "size" as "invisible". Any other size will return the null error. 

Thank you for the help @douglasjunior.
